### ISSUE TITLE
Unable to send ticket through freshdesk

### ISSUE THREAD

**Issue by oguzhanvarsak** [x74353/Amphetamine_Localization#1]
I tried to send a ticket for submitting translation of the application to Turkish via Freshdesk but I got this :

> We are sorry. You have been restricted from accessing this helpdesk page.

Is there anything I can do about translation?

Thank you.

**Comment by Altair-Bueno** [comment]
Having same issue. im interested on localising amphetamine to Spanish
<img width="1436" alt="Captura de pantalla 2020-11-15 a las 14 16 37" src="https://user-images.githubusercontent.com/67512202/99185931-3039ee00-274d-11eb-9ab6-0b28fd180326.png">

**Comment by x74353** [comment]
Not sure what is going on with the support site. I've submitted a support request to the company who offers the service. @Altair-Bueno thank you for offering to help out with a Spanish translation. There is a partial Spanish translation done which I can send to you if you'd like, or you can start fresh. Just let me know! Hopefully, I can get the support site working again soon.
![CleanShot 2020-11-16 at 10 21 29](https://user-images.githubusercontent.com/1432223/99272242-8febd400-27f5-11eb-9a6e-feb7a2f16f78.png)

**Comment by Altair-Bueno** [comment]
Nah, i think i'll start fresh. I want a nice and consistent translation across all strings. Not sure where the original author is from. Although Spanish is still Spanish, some things are different all around the world. 

How do i send you the files whenever they are ready (in case freshdesk doesn't work)?

**Comment by x74353** [comment]
@Altair-Bueno Freshdesk should be working now. Thanks!! I've updated the Localizable.strings file in this repo to the latest version. If you've already started work on an older version, don't worry. There are only a couple of changes that I can manage on my own once translation is complete.

**Comment by x74353** [comment]
@oguzhanvarsak The Freshdesk site should be working now. Thank you!
